// Generated by gencpp from file tip/ControlMsg.msg
// DO NOT EDIT!


#ifndef TIP_MESSAGE_CONTROLMSG_H
#define TIP_MESSAGE_CONTROLMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace tip
{
template <class ContainerAllocator>
struct ControlMsg_
{
  typedef ControlMsg_<ContainerAllocator> Type;

  ControlMsg_()
    : header()
    , ID(0)
    , translation(0.0)
    , rotation(0.0)  {
    }
  ControlMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ID(0)
    , translation(0.0)
    , rotation(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _ID_type;
  _ID_type ID;

   typedef float _translation_type;
  _translation_type translation;

   typedef float _rotation_type;
  _rotation_type rotation;





  typedef boost::shared_ptr< ::tip::ControlMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tip::ControlMsg_<ContainerAllocator> const> ConstPtr;

}; // struct ControlMsg_

typedef ::tip::ControlMsg_<std::allocator<void> > ControlMsg;

typedef boost::shared_ptr< ::tip::ControlMsg > ControlMsgPtr;
typedef boost::shared_ptr< ::tip::ControlMsg const> ControlMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tip::ControlMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tip::ControlMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tip

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'tip': ['/home/qingchen/catkin_ws/src/tip/msg'], 'qualisys': ['/home/qingchen/catkin_ws/src/qualisys/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tip::ControlMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tip::ControlMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tip::ControlMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tip::ControlMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tip::ControlMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tip::ControlMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tip::ControlMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a587840309303d749a13367bdb070c0c";
  }

  static const char* value(const ::tip::ControlMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa587840309303d74ULL;
  static const uint64_t static_value2 = 0x9a13367bdb070c0cULL;
};

template<class ContainerAllocator>
struct DataType< ::tip::ControlMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tip/ControlMsg";
  }

  static const char* value(const ::tip::ControlMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tip::ControlMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
int32 ID\n\
float32 translation\n\
float32 rotation\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::tip::ControlMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tip::ControlMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ID);
      stream.next(m.translation);
      stream.next(m.rotation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tip::ControlMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tip::ControlMsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ID: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ID);
    s << indent << "translation: ";
    Printer<float>::stream(s, indent + "  ", v.translation);
    s << indent << "rotation: ";
    Printer<float>::stream(s, indent + "  ", v.rotation);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TIP_MESSAGE_CONTROLMSG_H
