// Generated by gencpp from file tip/UnicycleInfoMsg.msg
// DO NOT EDIT!


#ifndef TIP_MESSAGE_UNICYCLEINFOMSG_H
#define TIP_MESSAGE_UNICYCLEINFOMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <tip/UnicycleInfoStruct.h>

namespace tip
{
template <class ContainerAllocator>
struct UnicycleInfoMsg_
{
  typedef UnicycleInfoMsg_<ContainerAllocator> Type;

  UnicycleInfoMsg_()
    : header()
    , packet()  {
    }
  UnicycleInfoMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , packet(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::tip::UnicycleInfoStruct_<ContainerAllocator>  _packet_type;
  _packet_type packet;





  typedef boost::shared_ptr< ::tip::UnicycleInfoMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tip::UnicycleInfoMsg_<ContainerAllocator> const> ConstPtr;

}; // struct UnicycleInfoMsg_

typedef ::tip::UnicycleInfoMsg_<std::allocator<void> > UnicycleInfoMsg;

typedef boost::shared_ptr< ::tip::UnicycleInfoMsg > UnicycleInfoMsgPtr;
typedef boost::shared_ptr< ::tip::UnicycleInfoMsg const> UnicycleInfoMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tip::UnicycleInfoMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tip::UnicycleInfoMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tip

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'tip': ['/home/qingchen/catkin_ws/src/tip/msg'], 'qualisys': ['/home/qingchen/catkin_ws/src/qualisys/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tip::UnicycleInfoMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tip::UnicycleInfoMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tip::UnicycleInfoMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tip::UnicycleInfoMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tip::UnicycleInfoMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tip::UnicycleInfoMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tip::UnicycleInfoMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "17316b31155b675ddbba08720370f6af";
  }

  static const char* value(const ::tip::UnicycleInfoMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x17316b31155b675dULL;
  static const uint64_t static_value2 = 0xdbba08720370f6afULL;
};

template<class ContainerAllocator>
struct DataType< ::tip::UnicycleInfoMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tip/UnicycleInfoMsg";
  }

  static const char* value(const ::tip::UnicycleInfoMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tip::UnicycleInfoMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
UnicycleInfoStruct packet\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: tip/UnicycleInfoStruct\n\
Header header\n\
int32 TransmitterID\n\
float32 AgentPosX\n\
float32 AgentPosY\n\
float32 AgentTheta\n\
float32 VirtualCenterX\n\
float32 VirtualCenterY\n\
float32 V_BLF\n\
";
  }

  static const char* value(const ::tip::UnicycleInfoMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tip::UnicycleInfoMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.packet);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UnicycleInfoMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tip::UnicycleInfoMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tip::UnicycleInfoMsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "packet: ";
    s << std::endl;
    Printer< ::tip::UnicycleInfoStruct_<ContainerAllocator> >::stream(s, indent + "  ", v.packet);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TIP_MESSAGE_UNICYCLEINFOMSG_H
