// Generated by gencpp from file voronoi_draw/CentralizedMsg.msg
// DO NOT EDIT!


#ifndef VORONOI_DRAW_MESSAGE_CENTRALIZEDMSG_H
#define VORONOI_DRAW_MESSAGE_CENTRALIZEDMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace voronoi_draw
{
template <class ContainerAllocator>
struct CentralizedMsg_
{
  typedef CentralizedMsg_<ContainerAllocator> Type;

  CentralizedMsg_()
    : valueArr()  {
    }
  CentralizedMsg_(const ContainerAllocator& _alloc)
    : valueArr(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _valueArr_type;
  _valueArr_type valueArr;





  typedef boost::shared_ptr< ::voronoi_draw::CentralizedMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::voronoi_draw::CentralizedMsg_<ContainerAllocator> const> ConstPtr;

}; // struct CentralizedMsg_

typedef ::voronoi_draw::CentralizedMsg_<std::allocator<void> > CentralizedMsg;

typedef boost::shared_ptr< ::voronoi_draw::CentralizedMsg > CentralizedMsgPtr;
typedef boost::shared_ptr< ::voronoi_draw::CentralizedMsg const> CentralizedMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::voronoi_draw::CentralizedMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::voronoi_draw::CentralizedMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace voronoi_draw

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'voronoi_draw': ['/home/qingchen/catkin_ws/src/voronoi_draw/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::voronoi_draw::CentralizedMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::voronoi_draw::CentralizedMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::voronoi_draw::CentralizedMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::voronoi_draw::CentralizedMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::voronoi_draw::CentralizedMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::voronoi_draw::CentralizedMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::voronoi_draw::CentralizedMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "06400f478916f41614d3caf5ce38a451";
  }

  static const char* value(const ::voronoi_draw::CentralizedMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x06400f478916f416ULL;
  static const uint64_t static_value2 = 0x14d3caf5ce38a451ULL;
};

template<class ContainerAllocator>
struct DataType< ::voronoi_draw::CentralizedMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "voronoi_draw/CentralizedMsg";
  }

  static const char* value(const ::voronoi_draw::CentralizedMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::voronoi_draw::CentralizedMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] valueArr\n\
";
  }

  static const char* value(const ::voronoi_draw::CentralizedMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::voronoi_draw::CentralizedMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.valueArr);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CentralizedMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::voronoi_draw::CentralizedMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::voronoi_draw::CentralizedMsg_<ContainerAllocator>& v)
  {
    s << indent << "valueArr[]" << std::endl;
    for (size_t i = 0; i < v.valueArr.size(); ++i)
    {
      s << indent << "  valueArr[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.valueArr[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // VORONOI_DRAW_MESSAGE_CENTRALIZEDMSG_H
