set(_CATKIN_CURRENT_PACKAGE "voronoi_draw")
set(voronoi_draw_VERSION "0.0.0")
set(voronoi_draw_MAINTAINER "jerry <jerry@todo.todo>")
set(voronoi_draw_PACKAGE_FORMAT "2")
set(voronoi_draw_BUILD_DEPENDS "rospy" "std_msgs" "message_generation")
set(voronoi_draw_BUILD_EXPORT_DEPENDS "rospy" "std_msgs")
set(voronoi_draw_BUILDTOOL_DEPENDS "catkin")
set(voronoi_draw_BUILDTOOL_EXPORT_DEPENDS )
set(voronoi_draw_EXEC_DEPENDS "rospy" "std_msgs")
set(voronoi_draw_RUN_DEPENDS "rospy" "std_msgs")
set(voronoi_draw_TEST_DEPENDS )
set(voronoi_draw_DOC_DEPENDS )
set(voronoi_draw_URL_WEBSITE "")
set(voronoi_draw_URL_BUGTRACKER "")
set(voronoi_draw_URL_REPOSITORY "")
set(voronoi_draw_DEPRECATED "")