set(_CATKIN_CURRENT_PACKAGE "tip")
set(tip_VERSION "0.0.0")
set(tip_MAINTAINER "zengjiezhang <zengjiezhang@todo.todo>")
set(tip_PACKAGE_FORMAT "1")
set(tip_BUILD_DEPENDS "message_generation" "qualisys" "roscpp")
set(tip_BUILD_EXPORT_DEPENDS "message_runtime" "qualisys" "roscpp")
set(tip_BUILDTOOL_DEPENDS "catkin")
set(tip_BUILDTOOL_EXPORT_DEPENDS )
set(tip_EXEC_DEPENDS "message_runtime" "qualisys" "roscpp")
set(tip_RUN_DEPENDS "message_runtime" "qualisys" "roscpp")
set(tip_TEST_DEPENDS )
set(tip_DOC_DEPENDS )
set(tip_URL_WEBSITE "")
set(tip_URL_BUGTRACKER "")
set(tip_URL_REPOSITORY "")
set(tip_DEPRECATED "")